### ISSUE TITLE
WCAG 3 etc...

### ISSUE THREAD

**Issue by Myndex** [proteanstudio/contrast-tools#26]
I just wanted to follow up with WCAG3 status — it wasn't just APCA, **_all_** guidelines have been removed from the working draft, and this is done because the entire concept of the conformance model for WCAG3 is changing rather substantially. This does not mean that APCA is removed from the eventual standard.

It's useful to point out that APCA is also developing as an independent standard, the [**APCA Readability Criterion**](https://readtech.org/ARC/), and feel free to link to it, just please indicate that it is a draft standard at this point.

**Comment by abdulmhamid** [comment]
@Myndex Thank you for the clarification. We will look through ARC and update the language to reflect your notes soon.

**Comment by abdulmhamid** [comment]
Resolved by #29 and merged in #31.
